import { DB_NAME, openDatabase, readLedger, updateCategory, updatePayment, editExpense, exportPortableBackup } from '../local-first/ledger.mjs';
import { STORES } from '../local-first/idb.mjs';
const lines=[];
const check=(value,message)=>{if(!value)throw new Error(message);};
const report=document.createElement('pre');report.id='settings-test-result';document.body.prepend(report);
const open=indexedDB.open.bind(indexedDB);
indexedDB.open=(name,version)=>open(name===DB_NAME?DB_NAME+'-settings-ui-checks':name,version);
const db=await openDatabase();
const tx=db.transaction(STORES,'readwrite');for(const section of STORES)tx.objectStore(section).clear();
await new Promise((resolve,reject)=>{tx.oncomplete=resolve;tx.onabort=reject;});
const wait=async action=>{
  action();
  await new Promise((resolve,reject)=>{
    const observer=new MutationObserver(()=>{if(document.querySelector('#status').textContent.includes('正在儲存'))return;observer.disconnect();clearTimeout(timeout);resolve();});
    const timeout=setTimeout(()=>{observer.disconnect();reject(new Error('Write timeout'));},5000);
    observer.observe(document.body,{subtree:true,attributes:true,childList:true});
  });
};
const option=(name,value)=>[...document.querySelector(`[name="${name}"]`).options].some(row=>row.textContent===value);
const row=(type,name)=>[...document.querySelectorAll(`#${type}-list li`)].find(row=>row.querySelector('span').textContent===name);
const setting=(type,op,name)=>row(type,name).querySelector(`[data-operation="${op}"]`).click();
const confirm=()=>document.querySelector('#settings-form').requestSubmit();
try{
  await import('../local-first/page.mjs');document.querySelector('#start-ledger').click();
  await new Promise(resolve=>{const observer=new MutationObserver(()=>{if(document.querySelector('#ledger-page').hidden)return;observer.disconnect();resolve();});observer.observe(document.body,{subtree:true,attributes:true});});
  check(document.querySelector('#ledger-settings')?.tagName==='DETAILS','Missing native settings');
  check(!document.querySelector('#ledger-settings').open,'Settings must start collapsed');
  document.querySelector('#ledger-settings').open=true;
  const categoryForm=document.querySelector('#category-add');
  categoryForm.elements.name.value='總額';await wait(()=>categoryForm.requestSubmit());
  check(categoryForm.elements.name.value==='總額' && document.querySelector('#settings-error').textContent,'Validation input/error lost');
  check((await readLedger(db)).categories.length===0,'Invalid category wrote');
  categoryForm.elements.name.value='合成分類';await wait(()=>categoryForm.requestSubmit());
  check(option('category','合成分類') && categoryForm.elements.name.value==='','New category options/reset');
  lines.push('native collapsed settings, invalid input retained and category options update');
  const paymentForm=document.querySelector('#payment-add');paymentForm.elements.name.value='合成卡';await wait(()=>paymentForm.requestSubmit());
  check(option('payment_source_id','合成卡'),'New payment option');
  check(!row('payment','現金').querySelector('button') && !row('payment','未指定').querySelector('button'),'Reserved controls exposed');
  const form=document.querySelector('#expense-form');form.elements.amount.value='12.34';form.elements.note.value='合成帳目';form.elements.category.value='合成分類';
  form.elements.payment_source_id.value=(await readLedger(db)).payment_sources.at(-1).id;
  await wait(()=>form.requestSubmit());
  setting('category','rename','合成分類');document.querySelector('#setting-name').value='合成新版';
  const before=await exportPortableBackup(db);document.querySelector('#cancel-setting').click();
  check((await exportPortableBackup(db)).toString()===before.toString(),'Cancel wrote');
  setting('category','rename','合成分類');document.querySelector('#setting-name').value='合成新版';await wait(confirm);
  check(option('category','合成新版') && !option('category','合成分類'),'Rename options');
  check((await readLedger(db)).expenses[0].category==='合成新版','Rename expense');
  setting('payment','rename','合成卡');document.querySelector('#setting-name').value='合成新卡';await wait(confirm);
  check(option('payment_source_id','合成新卡') && (await readLedger(db)).expenses[0].payment_source_name==='合成卡','Payment snapshot rewritten');
  setting('category','disable','合成新版');await wait(confirm);
  setting('payment','disable','合成新卡');await wait(confirm);
  check(!option('category','合成新版') && !option('payment_source_id','合成新卡'),'Disabled option still available');
  document.querySelector('#expenses button').click();
  check(form.elements.category.value==='合成新版' && form.elements.payment_source_id.value==='','Old entry original choice lost');
  form.elements.note.value='更改合成';await wait(()=>form.requestSubmit());
  check((await readLedger(db)).expenses[0].payment_source_name==='合成卡','Edit lost original snapshot');
  lines.push('add/confirmed rename/disable/cancel, original inactive choices and payment snapshots');
  categoryForm.elements.name.value='<svg/onload=x=1>';await wait(()=>categoryForm.requestSubmit());
  paymentForm.elements.name.value='<img src=x onerror=alert(2)>';await wait(()=>paymentForm.requestSubmit());
  check(!document.querySelector('#ledger-settings svg,#ledger-settings img'),'Unsafe DOM');
  check(row('category','<svg/onload=x=1>') && option('category','<svg/onload=x=1>') && !window.x,'Malicious category not accepted as safe text');
  check(!performance.getEntriesByType('resource').some(row=>new URL(row.name).pathname.endsWith('/x')),'Unsafe request');
  check(performance.getEntriesByType('resource').every(row=>new URL(row.name).origin===location.origin),'External request');
  lines.push('malicious category/payment displayed as text without requests');
  categoryForm.elements.name.value='編輯競態';await wait(()=>categoryForm.requestSubmit());
  form.elements.amount.value='1.23';form.elements.note.value='分頁 A';form.elements.category.value='編輯競態';await wait(()=>form.requestSubmit());
  document.querySelector('#expenses button').click();
  let raceState=await readLedger(db), racing=raceState.expenses.at(-1);
  await editExpense(db,racing.id,racing.revision,{amount:'4.56',note:'分頁 B',category:'交通',spent_on:racing.spent_on,payment_source_id:''},racing.spent_on);
  setting('category','rename','編輯競態');document.querySelector('#setting-name').value='競態新名';await wait(confirm);
  form.elements.note.value='不能覆蓋 B';await wait(()=>form.requestSubmit());
  check(document.querySelector('#error').textContent.includes('重新載入'),'Category rename forged stale expense revision');
  const raceAfter=(await readLedger(db)).expenses.at(-1);
  check(raceAfter.note==='分頁 B' && raceAfter.category==='交通' && raceAfter.cents==='456','Stale expense overwrote another page');
  document.querySelector('#cancel-edit').click();
  lines.push('category rename cannot advance an unrelated concurrent expense revision');
  categoryForm.elements.name.value='正常編輯';await wait(()=>categoryForm.requestSubmit());
  form.elements.amount.value='7.89';form.elements.note.value='保留草稿';form.elements.category.value='正常編輯';await wait(()=>form.requestSubmit());
  document.querySelector('#expenses button').click();form.elements.note.value='更改草稿';
  setting('category','rename','正常編輯');document.querySelector('#setting-name').value='正常新名';await wait(confirm);
  check(form.elements.note.value==='更改草稿' && form.elements.category.value==='正常新名','Own rename lost draft');
  await wait(()=>form.requestSubmit());
  check((await readLedger(db)).expenses.at(-1).note==='更改草稿','Own rename incorrectly blocks edit');
  const put=IDBObjectStore.prototype.put, beforeFailure=await exportPortableBackup(db);
  setting('category','rename','餐飲');document.querySelector('#setting-name').value='回滾名稱';
  IDBObjectStore.prototype.put=()=>{throw new DOMException('PRIVATE-DETAIL','QuotaExceededError');};
  try{await wait(confirm);}finally{IDBObjectStore.prototype.put=put;}
  check(document.querySelector('#settings-dialog').open && document.querySelector('#setting-name').value==='回滾名稱','Failed dialog lost input');
  check(document.querySelector('#setting-error').textContent && !document.querySelector('#setting-error').textContent.includes('PRIVATE-DETAIL'),'Raw failure leaked');
  check((await exportPortableBackup(db)).toString()===beforeFailure.toString(),'UI failure wrote');
  document.querySelector('#cancel-setting').click();
  lines.push('own rename retains editing draft; failed confirmation retains input and hides storage details');
  let state=await readLedger(db);await updateCategory(db,state.categories,'add',null,'另一分頁');
  categoryForm.elements.name.value='保留舊狀態';await wait(()=>categoryForm.requestSubmit());
  check(categoryForm.elements.name.value==='保留舊狀態' && document.querySelector('#settings-error').textContent.includes('重新載入'),'Stale category input not rejected');
  state=await readLedger(db);await updatePayment(db,state.payment_sources,'add',null,'另一分頁卡');
  paymentForm.elements.name.value='保留舊卡';await wait(()=>paymentForm.requestSubmit());
  check(paymentForm.elements.name.value==='保留舊卡' && document.querySelector('#settings-error').textContent.includes('重新載入'),'Stale payment input not rejected');
  lines.push('stale page category and payment rejected with retained inputs');
  report.textContent='PASS：'+lines.length+' 組設定畫面驗證\n'+lines.join('\n');
}catch(error){report.textContent='FAIL：'+error.message+'\n'+lines.join('\n');throw error;}
finally{db.close();}
