import {openDatabase,readLedgerIfPresent,exportPortableBackup} from '../local-first/ledger.mjs';
import {STORES,addState} from '../local-first/idb.mjs';
import {readBackup} from '../local-first/backup.mjs';
import {comparisonDefaults} from '../local-first/comparison.mjs';
const q=selector=>document.querySelector(selector),check=(value,message)=>{if(!value)throw new Error(message);};
const report=document.createElement('pre');report.id='comparison-test-result';document.body.prepend(report);
const lines=[],db=await openDatabase(),transaction=IDBDatabase.prototype.transaction;
const formatToParts=Intl.DateTimeFormat.prototype.formatToParts;
const wait=predicate=>new Promise((resolve,reject)=>{if(predicate()){resolve();return;}const observer=new MutationObserver(()=>{if(predicate()){observer.disconnect();clearTimeout(timer);resolve();}}),timer=setTimeout(()=>{observer.disconnect();reject(new Error('Comparison UI timeout'));},8000);observer.observe(document.body,{subtree:true,childList:true,attributes:true,characterData:true});});
try{
  check(await readLedgerIfPresent(db)===null,'Requires a fresh synthetic origin; never overwrite a ledger');
  const fixture=readBackup(new Uint8Array(await(await fetch('/tests/fixtures/portable_life_ledger.json')).arrayBuffer()));
  const state={format:'local-first-test-ledger',version:2,owner:'local-test-owner',...fixture.data};
  const base=state.expenses[0];
  state.expenses.forEach(row=>{row.cents='1';});
  for(let i=0;i<65;i++)state.expenses.push({...base,id:`compare-${i}`,spent_on:'2024-02-29',cents:'1',note:'Compare [x]',category:'合成比較',revision:0});
  state.expenses.push({...base,id:'compare-b',spent_on:'2024-01-31',cents:'100',note:'Compare [x]',category:'<img src=x onerror=alert(1)>',revision:0});
  state.expenses.push({...base,id:'compare-big',spent_on:'2024-02-29',cents:'9223372036854775807',note:'Extreme',revision:0});
  const tx=db.transaction(STORES,'readwrite');addState(tx,state);
  await new Promise((resolve,reject)=>{tx.oncomplete=resolve;tx.onabort=reject;});
  const backupText=async()=>new TextDecoder().decode(await exportPortableBackup(db));
  const raw=async()=>{const tx=db.transaction(STORES,'readonly'),rows={};for(const name of STORES)tx.objectStore(name).getAll().onsuccess=event=>{rows[name]=event.target.result;};await new Promise((resolve,reject)=>{tx.oncomplete=resolve;tx.onabort=reject;});return JSON.stringify(STORES.map(name=>rows[name]),(_key,value)=>typeof value==='bigint'?value.toString():value);};
  const before=await backupText(),rawBefore=await raw();
  await import('../local-first/page.mjs');await wait(()=>!q('#ledger-page').hidden);
  const form=q('#comparison-form');check(form,'Comparison form missing');
  const expected=comparisonDefaults(new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Taipei'}));
  for(const name of ['a_start','a_end','b_start','b_end'])check(form.elements[name].value===expected[name],'Whole month defaults');
  check(q('#comparison-category').textContent.includes('（歷史）'),'Historical categories absent');
  lines.push('Taiwan defaults; historical categories; opening is read-only');
  let reads=0;IDBDatabase.prototype.transaction=function(...args){reads++;check(args[1]==='readonly','Comparison wrote data');return transaction.apply(this,args);};
  form.elements.a_start.value='2025-01-02';form.elements.a_end.value='2025-01-01';form.requestSubmit();
  await wait(()=>q('#comparison-error').textContent.length>0);check(reads===0&&form.elements.a_start.value==='2025-01-02','Invalid input read/lost input');
  form.elements.a_start.value='2024-02-01';form.elements.a_end.value='2024-02-29';form.elements.b_start.value='2024-01-01';form.elements.b_end.value='2024-01-31';form.elements.keyword.value='compare [x]';
  form.elements.a_start.setCustomValidity('synthetic invalid');form.requestSubmit();await wait(()=>q('#comparison-error').textContent.includes('日期'));check(reads===0,'Native invalid read');form.elements.a_start.setCustomValidity('');
  lines.push('Invalid dates retain input and perform no database read');
  const submit=async()=>{reads=0;let todayCalls=0;Intl.DateTimeFormat.prototype.formatToParts=function(...args){if(this.resolvedOptions().timeZone==='Asia/Taipei')todayCalls++;return formatToParts.apply(this,args);};try{form.requestSubmit();await wait(()=>!form.querySelector('button').disabled&&q('#comparison-results').childElementCount>0);check(reads===1&&todayCalls===1,'Must use one snapshot and one Taiwan today');}finally{Intl.DateTimeFormat.prototype.formatToParts=formatToParts;}};
  await submit();check(q('#comparison-results').textContent.includes('65 筆')&&q('#comparison-results').textContent.includes('0.65 元'),'50-row cap or inexact sum');
  check(q('#comparison-results').textContent.includes('−0.35 元'),'Exact difference missing');
  check(q('#comparison-results').querySelector('img')===null,'Untrusted category executed');
  check(q('#comparison-results').textContent.includes('<img src=x onerror=alert(1)>'),'Unsafe text lost');
  const chartStatus=q('#comparison-chart-status').textContent;
  const failed=chartStatus.includes('無法載入');
  check(failed||q('#comparison-results').querySelectorAll('canvas').length===4,'Charts or safe fallback missing');
  check(failed||q('#comparison-results').querySelectorAll('.comparison-chart[hidden]').length===0,'Pie collapsed/hidden');
  check(q('#comparison-results').querySelector('table')&&q('#comparison-results').querySelector('details'),'Text fallback absent');
  lines.push('One snapshot, 65 records, exact cents, XSS-safe tables; '+(failed?'asset failure keeps text':'four local charts and visible pies'));
  form.elements.category.value='合成比較';await submit();check(q('#comparison-results').textContent.includes('65 筆')&&!q('#comparison-results').textContent.includes('<img'),'Category AND keyword failed');lines.push('Shared category/keyword AND and single-category chart');
  form.elements.keyword.value='no match';await submit();check(q('#comparison-results').textContent.includes('0 元')&&q('#comparison-results').querySelectorAll('canvas').length===0,'Empty chart misleading');lines.push('Two empty periods have text zero, no blank chart');
  form.elements.a_start.value='2099-01-01';form.elements.a_end.value='2099-01-31';await submit();check(q('#comparison-results').textContent.includes('期間尚未開始')&&q('#comparison-results').textContent.includes('無法比較'),'Future treated as zero');lines.push('Future unknown suppresses comparison');
  form.elements.category.value='';form.elements.keyword.value='Extreme';form.elements.a_start.value='2024-02-01';form.elements.a_end.value='2024-02-29';await submit();check(q('#comparison-results').textContent.includes('92,233,720,368,547,758.07 元')&&q('#comparison-chart-status').textContent.includes('安全繪圖')&&q('#comparison-results').querySelectorAll('canvas').length===0,'Extreme money must stay exact');lines.push('Signed-64-bit money safely falls back to exact text');
  form.elements.keyword.value='compare [x]';form.elements.a_start.value='0001-01-01';form.elements.a_end.value='9999-12-31';await submit();check(q('#comparison-results details tbody').children.length===500&&!q('#comparison-results details button').hidden,'Long range must use lazy text pages');q('#comparison-results details button').click();check(q('#comparison-results details tbody').children.length===1000,'Complete zero days inaccessible');lines.push('Long valid ranges retain all statistics and page exact zero days');
  IDBDatabase.prototype.transaction=function(){throw new DOMException('synthetic unavailable','QuotaExceededError');};form.requestSubmit();await wait(()=>q('#comparison-error').textContent.includes('無法比較支出'));check(form.elements.keyword.value==='compare [x]'&&q('#comparison-results').childElementCount===0,'Read failure lost input or left stale results');lines.push('IndexedDB failure keeps input and shows a fixed safe error');
  IDBDatabase.prototype.transaction=transaction;
  check(before===await backupText()&&rawBefore===await raw(),'Comparison changed complete backup');lines.push('Complete nine-section backup and raw rows/metadata byte-identical after every readonly query');
  form.elements.category.value='';form.elements.keyword.value='compare [x]';form.elements.a_start.value='2024-02-01';form.elements.a_end.value='2024-02-29';form.requestSubmit();await wait(()=>!form.querySelector('button').disabled);
  check(!location.search&&!document.querySelector('#comparison-results img'),'Data entered a URL or unsafe DOM');check(performance.getEntriesByType('resource').every(row=>new URL(row.name).origin===location.origin),'External resource requested');lines.push('No query URL, external request or unsafe DOM');
  report.textContent=`PASS ${lines.length}\n`+lines.join('\n');report.dataset.done='pass';
}catch(failure){report.textContent='FAIL comparison synthetic validation: '+(lines.at(-1)||'initialization')+' ['+failure.name+']'+(failure instanceof ReferenceError?' '+failure.message:'');report.dataset.done='fail';}
finally{IDBDatabase.prototype.transaction=transaction;Intl.DateTimeFormat.prototype.formatToParts=formatToParts;db.close();}
