import {DB_NAME,openDatabase,readLedger,updateFixed,updateCategory,exportPortableBackup,taiwanToday} from '../local-first/ledger.mjs';
import {emptyData} from '../local-first/backup.mjs';
import {STORES,addState} from '../local-first/idb.mjs';
const check=(value,message)=>{if(!value)throw new Error(message);};
const report=document.createElement('pre');report.id='fixed-test-result';document.body.prepend(report);
const open=indexedDB.open.bind(indexedDB);indexedDB.open=(name,version)=>open(name===DB_NAME?DB_NAME+'-fixed-ui-checks':name,version);
const db=await openDatabase(),today=taiwanToday(),month=today.slice(0,7),lines=[];
const initial={format:'local-first-test-ledger',version:2,owner:'local-test-owner',...emptyData(),payment_sources:[{id:'p_cash',name:'現金',active:1}]};
const tx=db.transaction(STORES,'readwrite');for(const section of STORES)tx.objectStore(section).clear();addState(tx,initial);
await new Promise((resolve,reject)=>{tx.oncomplete=resolve;tx.onabort=reject;});
const wait=async action=>{const complete=new Promise((resolve,reject)=>{const observer=new MutationObserver(()=>{
  if(document.querySelector('#status').textContent.includes('正在儲存'))return;observer.disconnect();clearTimeout(timeout);resolve();});
  const timeout=setTimeout(()=>{observer.disconnect();reject(new Error('Write timeout'));},5000);observer.observe(document.body,{subtree:true,attributes:true,childList:true});});action();await complete;};
const current=()=>document.querySelector('#fixed-list > li');
try {
  const before=(await exportPortableBackup(db)).toString();await import('../local-first/page.mjs');
  check(document.querySelector('#fixed-settings')?.tagName==='DETAILS'&&!document.querySelector('#fixed-settings').open,'Missing native collapsed fixed settings');
  check((await exportPortableBackup(db)).toString()===before,'Page implicitly posted/wrote');
  document.querySelector('#ledger-settings').open=true;document.querySelector('#fixed-settings').open=true;
  const form=document.querySelector('#fixed-form');
  form.elements.name.value='<img src=x onerror="window.fixedXss=1">';form.elements.amount.value='12.34';form.elements.category.value='居住';form.elements.due_day.value='1';
  form.elements.name.focus();
  await wait(()=>{form.requestSubmit();form.requestSubmit();});
  let state=await readLedger(db);check(state.recurring_rules.length===1&&state.expenses.length===0,'Repeated add click/implicit catchup');
  check(current().textContent.includes('<img src=x')&&!current().querySelector('img'),'Unsafe item HTML');
  check(current().textContent.includes('目前設定')&&form.elements.name.value==='','Save not reset');
  check(document.activeElement===form.elements.name,'Fixed keyboard focus lost after save');
  lines.push('collapsed native settings, read-only load, repeated-submit guard, malicious name safe text and explicit create');
  current().querySelector('[data-operation="update"]').click();
  check(form.elements.start_month.disabled&&form.elements.start_month.value===month,'Start is editable or changed');
  form.elements.name.value='下月固定';form.elements.amount.value='20.01';
  await wait(()=>form.requestSubmit());
  check(current().textContent.includes('下月生效設定')&&current().textContent.includes('20.01 元')&&current().textContent.includes('12.34 元'),'Current/pending not distinguished');
  document.querySelector('#search-form').elements.start.value=month+'-01';
  document.querySelector('#search-form').requestSubmit();
  await new Promise(resolve=>{const observer=new MutationObserver(()=>{if(document.querySelector('#search-count').textContent){observer.disconnect();resolve();}});observer.observe(document.querySelector('#search-count'),{childList:true});});
  await wait(()=>{document.querySelector('#fixed-sync').click();document.querySelector('#fixed-sync').click();});
  state=await readLedger(db);check(state.expenses.length===1&&state.actions.length===1,'Repeated sync duplicate');
  check(document.querySelector('#budget-spent').textContent.includes('12.34 元'),'Budget not refreshed');
  check(document.querySelector('#search-count').textContent.includes('1 筆')&&document.querySelector('#calendar-grid [data-day="'+month+'-01"] .marker'),'Search/calendar not refreshed');
  check(document.querySelectorAll('#expenses button').length===2,'Automatic expense lacks shared edit/delete');
  lines.push('next-month settings preserve current; explicit repeated catch-up updates exact budget/search/calendar; automatic rows read-only');
  current().querySelector('[data-operation="stop"]').click();document.querySelector('#cancel-fixed-stop').click();
  check((await readLedger(db)).recurring_rules[0].active===1,'Cancel disabled rule');
  current().querySelector('[data-operation="update"]').click();form.elements.name.value='保留失敗輸入';form.elements.amount.value='0';
  await wait(()=>form.requestSubmit());check(form.elements.amount.value==='0'&&form.elements.name.value==='保留失敗輸入'&&document.querySelector('#fixed-error').textContent,'Invalid input lost');
  form.elements.amount.value='30';const stale=(await readLedger(db)).recurring_rules[0],other=await openDatabase();
  await updateFixed(other,'update',stale.id,stale.revision,{name:'其他頁',amount:'40',category:'居住',due_day:1});other.close();
  await wait(()=>form.requestSubmit());check(document.querySelector('#fixed-error').textContent.includes('重新載入')&&form.elements.name.value==='保留失敗輸入','Stale overwrite/form lost');
  document.querySelector('#cancel-fixed-edit').click();
  current().querySelector('[data-operation="stop"]').click();
  await wait(()=>document.querySelector('#confirm-fixed-stop').click());
  check(document.querySelector('#fixed-stop-error').textContent.includes('重新載入')&&document.querySelector('#fixed-stop-dialog').open,'Stale stop silently succeeded');
  document.querySelector('#cancel-fixed-stop').click();
  lines.push('cancel stop writes nothing; invalid/stale edit retains input; stale confirmation refuses newer rule');
  const put=IDBObjectStore.prototype.put,prior=(await exportPortableBackup(db)).toString();
  IDBObjectStore.prototype.put=()=>{throw new DOMException('PRIVATE-DETAIL','QuotaExceededError');};
  try {form.elements.name.value='交易失敗';form.elements.amount.value='1';await wait(()=>form.requestSubmit());}finally{IDBObjectStore.prototype.put=put;}
  check(form.elements.name.value==='交易失敗'&&!document.querySelector('#fixed-error').textContent.includes('PRIVATE-DETAIL'),'Storage failure input/raw details');
  check((await exportPortableBackup(db)).toString()===prior,'Failed UI write changed backup');
  check(performance.getEntriesByType('resource').every(item=>new URL(item.name).origin===location.origin),'External resource');
  lines.push('failed transaction keeps form and safe message; backup unchanged and no third-party resource');
  await wait(()=>form.requestSubmit());
  state=await readLedger(db);const newest=state.recurring_rules.at(-1);
  await updateCategory(db,state.categories,'disable',newest.category);
  current().querySelector('[data-operation="update"]').click();form.elements.amount.value='2';
  await wait(()=>form.requestSubmit());
  current().querySelector('[data-operation="update"]').click();
  check(form.elements.category.selectedOptions[0].textContent.includes('停用，保留原值'),'Inactive target category not retained in select');
  document.querySelector('#cancel-fixed-edit').click();
  const beforeStop=(await readLedger(db)).expenses.length;
  current().querySelector('[data-operation="stop"]').click();await wait(()=>document.querySelector('#confirm-fixed-stop').click());
  state=await readLedger(db);
  check(!document.querySelector('#fixed-stop-dialog').open&&state.recurring_rules.at(-1).active===0,'Successful stop not confirmed');
  check(state.expenses.length===beforeStop+1&&state.expenses.at(-1).cents==='100','Stop failed to catch up current settings before disabling');
  check(!current().querySelector('button')&&current().textContent.includes('已停用，不會執行'),'Stopped rule has edit/reactivate or lost pending history');
  lines.push('inactive category is retained in edit; successful stop catches missing current expense, preserves pending and removes management controls');
  report.textContent='PASS：'+lines.length+' 組固定支出畫面驗證\n'+lines.join('\n');
}catch(error){report.textContent='FAIL：'+error.message;throw error;}finally{db.close();}
